# Site settings
title: Fan Blog
SEOTitle: SYY的博客 | Fan Blog
header-img: img/home-bg.jpg
email: 2233276965@qq.com
description: "关于前端与设计、黑客与画家 | SYY，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @FanSYY 的个人博客，与你一起发现更大的世界。"
keyword: "SYY, FanSYY, Fan, 鬼栈, fanwu, @fanpro, SYY的博客, Fan Blog, 博客, 个人网站, 互联网, Web, C++, 前端, 设计"
url: "https://huangxuan.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     fan
zhihu_username:     fan-89-41-15/activities
github_username:    keyou-fang
twitter_username:   fan
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: fan

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做笔记，<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "ddd大佬的博客",
        href: "https://www.luogu.org/blog/75165/"
    },{
        title: "蒟蒻lzh的博客",
        href: "https://hellojuruo.github.io/"
    },{
        title: "David's Game",
        href: "https://www.ruoyaowu.com/"
    }
]
